# Generated by Django 3.2.9 on 2021-12-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lizgalleryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name'], 'verbose_name': 'My gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lizgalleryapp.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lizgalleryapp.location'),
        ),
    ]
